name: Tests-coverage

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          if [ -d 'project' ]; then cd project && npm install; else echo 'Skip. The project directory does not exist'; fi

      - name: Run checks
        run: |
          if [ -d 'project' ]; then cd project && npm test && npm run lint; else echo 'Skip. The project directory does not exist'; fi

      - name: Code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test-coverage
          workingDirectory: ${{github.workspace}}/project
          coverageLocations: ${{github.workspace}}/project/coverage/coverage.xml:clover
          debug: true
